NumPy

NumPy - Numerical Python

NumPy is used for scientific computing with python. This can work on N-Dimensional arrays more efficiently.


list_1 = [1,2,3,4,5....]

Array - It is a collection of items stored in a specific memory locations.

Libraries in Python - Some extension added to python to make it more efficient.

In [ ]:
How it install any library in Python?
Synatx:

!pip install <library name>

In [ ]:
!pip install numpy

In [ ]:
How to import library?

import <library name> as 

also, use alias

import numpy as np

In [1]:
myList = [1,2,3]

In [4]:
type(myList)

list

In [ ]:
## converting list into numpy array

In [3]:
import numpy as np

In [4]:
n = np.array(myList)

In [ ]:
n.

In [7]:
print(n)

[1 2 3]


In [9]:
type(n)

numpy.ndarray

In [10]:
myList2 = np.array(myList)

In [11]:
print(myList2)

[1 2 3]


In [12]:
type(myList2)

numpy.ndarray

In [13]:
type(myList)

list

In [14]:
myList = np.array(myList)

In [15]:
type(myList)

numpy.ndarray

In [16]:
## Creating multi-Dimensional Array

In [17]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
print(list_of_lists)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
type(list_of_lists)

numpy.ndarray

In [20]:
## Numpy Functions

In [21]:
# Arrange Function

In [24]:
range(1,10)

range(1, 10)

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy Arange is similar to Python range but is more efficient - faster

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
for x in range(0,10,2):
    print(x)

0
2
4
6
8


In [32]:
## Numpy Zeros

In [ ]:
list_of_lists1 = np.array([[1,2,3],[4,5],[7,8,9]])

In [36]:
zeros = np.zeros(100)  # 1 x 100 matrix or 1D array

In [37]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [38]:
## Numpy Ones

In [39]:
ones = np.ones(100)

In [40]:
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [3]:
onez = np.ones((3,3))  ## 3 x 3 matrix - 3D array

In [4]:
print(onez)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
zeroz = np.zeros((5,5))

In [6]:
print(zeroz)  ## 5 x 5 matrix or 5D array

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
type(onez)

numpy.ndarray

In [9]:
## Numpy eye - Identity matrix

In [13]:
diag_ones = np.eye(5)

In [14]:
print(diag_ones)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
## Length of numpy array - it returns no of columns in matrix

In [16]:
len(diag_ones)

5

In [17]:
len(onez)

3

In [18]:
len(zeroz)

5

In [19]:
a = np.arange(10)

In [20]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
len(a)  ## in 1-D array it return no of elements 

10

In [ ]:
Numpy Array - Homogenous Type
Python List,Tuple,Dictionary - Heterogenous Type

In [5]:
## Numpy Reshape

In [ ]:
Reshape allows arrays tobe shaped into defnied rows and columns

In [6]:
nm = [1,2,3,4,5,6,7,8,9,10]

In [7]:
nm = np.array(nm)

In [8]:
print(nm)  ## 1x10 matrix

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
type(nm)

numpy.ndarray

In [10]:
len(nm)

10

In [11]:
nm.reshape(5,2)  ## converting 1D matrix into 5x2 matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
nm

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
## Reshape function never modifies the original Value

In [ ]:
## rows x columns = size of array

In [13]:
nm.reshape(4,2) 

ValueError: cannot reshape array of size 10 into shape (4,2)

In [14]:
## Numpy Linespace

Numpy Linespace returns evenly spaced values in float format

In [20]:
val_1 = np.linspace(0,7,10)

In [21]:
print(val_1)

[0.         0.77777778 1.55555556 2.33333333 3.11111111 3.88888889
 4.66666667 5.44444444 6.22222222 7.        ]


In [22]:
np.linspace(0,7,10)

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [23]:
## Numpy Resize

In [24]:
type(nm)

numpy.ndarray

In [25]:
nm

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
nm.resize(5,2)

In [27]:
nm

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
## Numpy resize modifies the original value

In [32]:
num_1 = [10,20,30,40,50,60,70,80,90,100]

In [33]:
num_1 = np.array(num_1)

In [34]:
num_1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
num_1.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [36]:
num_1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [37]:
num_1.resize(5,2)

In [38]:
num_1

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [39]:
## Generating Random number

In [42]:
np.random.rand(3,2) ## creates an array of given size with random values between 0 and 1

array([[0.7882784 , 0.72405422],
       [0.95376094, 0.64424186],
       [0.6139861 , 0.69559912]])

In [43]:
np.random.rand(3,2)

array([[0.96219364, 0.83293863],
       [0.35484907, 0.27780158],
       [0.95236621, 0.50083236]])

In [44]:
np.random.rand(3,2)

array([[0.58565598, 0.8354342 ],
       [0.55622054, 0.48415047],
       [0.87541032, 0.26041206]])

In [46]:
np.random.randn(3,3)  ## used values from standard normal distribution graph

array([[ 0.71702228, -0.18038252,  1.01235101],
       [-0.23076578,  0.64117327, -0.9164987 ],
       [-0.6332299 , -1.14967772, -0.08239956]])

In [47]:
np.random.randint(4,15,10)

array([ 6,  5,  9,  7,  6, 10,  4,  4,  9,  4])

In [48]:
np.random.randint(4,15,10)

array([ 7, 11,  5,  8, 10, 14, 11,  7, 10,  9])

In [49]:
np.random.randint(4,15,10) ## generate random integer values between 4 and 15 of 1 x 10 

array([ 8,  5, 10, 13,  6, 14, 13,  4,  8,  7])

In [50]:
np.random.randint(4,15,10)

array([14,  9,  4, 12, 12, 11, 13,  6, 13,  9])

In [55]:
np.random.randint(4,15,(4,3)) ## generate random integer values between 4 and 15 of shape 4 and 3

array([[14,  8,  7],
       [ 9, 10, 13],
       [14,  9, 11],
       [ 9,  9,  6]])

In [56]:
num_2 = np.random.randint(4,15,10)

In [ ]:
## Slicing and Indexing in Numpy

In [ ]:
## Indexing is same as that in Python

In [57]:
num_2

array([ 9,  9,  6,  7, 10,  5, 14,  9, 12, 14])

In [58]:
num_2[4] ## accessing elements using indexing

10

In [59]:
num_2[-3]

9

In [60]:
num_2[2:6] ## slicing in Python

array([ 6,  7, 10,  5])

In [61]:
num_2[3:]

array([ 7, 10,  5, 14,  9, 12, 14])

In [ ]:
## Finish Numpy remaining part and Python Array