NumPy

NumPy - Numerical Python

NumPy is used for scientific computing with python. This can work on N-Dimensional arrays more efficiently.


list_1 = [1,2,3,4,5....]

Array - It is a collection of items stored in a specific memory locations.

Libraries in Python - Some extension added to python to make it more efficient.

How it install any library in Python?
Synatx:

!pip install <library name>

In [ ]:
!pip install numpy

In [ ]:
How to import library?

import <library name> as 

also, use alias

import numpy as np

In [10]:
myList = [1,2,3]

In [11]:
type(myList)

list

In [12]:
## converting list into numpy array

In [13]:
import numpy as np

In [14]:
n = np.array(myList)

In [ ]:
n.

In [15]:
print(n)

[1 2 3]


In [16]:
type(n)

numpy.ndarray

In [17]:
myList2 = np.array(myList)

In [18]:
print(myList2)

[1 2 3]


In [19]:
type(myList2)

numpy.ndarray

In [20]:
type(myList)

list

In [21]:
myList = np.array(myList)

In [22]:
type(myList)

numpy.ndarray

In [23]:
## Creating multi-Dimensional Array

In [24]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
print(list_of_lists)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
type(list_of_lists)

numpy.ndarray

In [27]:
## Numpy Functions

In [28]:
# Arrange Function

In [29]:
range(1,10)

range(1, 10)

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [32]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy Arange is similar to Python range but is more efficient - faster

In [33]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [34]:
for x in range(0,10,2):
    print(x)

0
2
4
6
8


In [35]:
## Numpy Zeros

In [36]:
list_of_lists1 = np.array([[1,2,3],[4,5],[7,8,9]])

C:\Users\SK\AppData\Local\Temp\ipykernel_17952\636785961.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  list_of_lists1 = np.array([[1,2,3],[4,5],[7,8,9]])


In [37]:
zeros = np.zeros(100)  # 1 x 100 matrix or 1D array

In [38]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [39]:
## Numpy Ones

In [40]:
ones = np.ones(100)

In [41]:
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [42]:
onez = np.ones((3,3))  ## 3 x 3 matrix - 3D array

In [43]:
print(onez)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
zeroz = np.zeros((5,5))

In [45]:
print(zeroz)  ## 5 x 5 matrix or 5D array

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
type(onez)

numpy.ndarray

In [47]:
## Numpy eye - Identity matrix

In [48]:
diag_ones = np.eye(5)

In [49]:
print(diag_ones)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
## Length of numpy array - it returns no of columns in matrix

In [51]:
len(diag_ones)

5

In [52]:
len(onez)

3

In [53]:
len(zeroz)

5

In [54]:
a = np.arange(10)

In [55]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
len(a)  ## in 1-D array it return no of elements 

10

Numpy Array - Homogenous Type
Python List,Tuple,Dictionary - Heterogenous Type

In [63]:
## Numpy Reshape

Reshape allows arrays tobe shaped into defnied rows and columns

In [64]:
nm = [1,2,3,4,5,6,7,8,9,10]

In [65]:
nm = np.array(nm)

In [66]:
print(nm)  ## 1x10 matrix

[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
type(nm)

numpy.ndarray

In [68]:
len(nm)

10

In [69]:
nm.reshape(5,2)  ## converting 1D matrix into 5x2 matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
nm

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
## Reshape function never modifies the original Value

In [72]:
## rows x columns = size of array

In [73]:
nm.reshape(4,2) 

ValueError: cannot reshape array of size 10 into shape (4,2)

In [ ]:
## Numpy Linespace

Numpy Linespace returns evenly spaced values in float format

In [74]:
val_1 = np.linspace(0,7,10)

In [75]:
print(val_1)

[0.         0.77777778 1.55555556 2.33333333 3.11111111 3.88888889
 4.66666667 5.44444444 6.22222222 7.        ]


In [76]:
np.linspace(0,7,10)

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [77]:
## Numpy Resize

In [78]:
type(nm)

numpy.ndarray

In [79]:
nm

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
nm.resize(5,2)

In [81]:
nm

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [82]:
## Numpy resize modifies the original value

In [83]:
num_1 = [10,20,30,40,50,60,70,80,90,100]

In [84]:
num_1 = np.array(num_1)

In [85]:
num_1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [86]:
num_1.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [87]:
num_1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
num_1.resize(5,2)

In [89]:
num_1

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [90]:
## Generating Random number

In [91]:
np.random.rand(3,2) ## creates an array of given size with random values between 0 and 1

array([[0.35418441, 0.76748215],
       [0.91375869, 0.18318184],
       [0.60179087, 0.58790281]])

In [92]:
np.random.rand(3,2)

array([[0.23551022, 0.93647325],
       [0.17296633, 0.6749028 ],
       [0.64802756, 0.73857645]])

In [93]:
np.random.rand(3,2)

array([[0.48519508, 0.05913519],
       [0.10063624, 0.77768281],
       [0.2710128 , 0.2911918 ]])

In [94]:
np.random.randn(3,3)  ## used values from standard normal distribution graph

array([[-1.39653279,  0.20701417,  0.46579228],
       [-1.06799131,  1.08577216,  0.54873813],
       [-1.54478739, -0.61342327, -1.65434701]])

In [95]:
np.random.randint(4,15,10)

array([12, 14, 11,  7, 11,  9,  7, 14, 10,  8])

In [96]:
np.random.randint(4,15,10)

array([12,  4, 14, 10,  5,  9, 11,  9,  5, 11])

In [97]:
np.random.randint(4,15,10) ## generate random integer values between 4 and 15 of 1 x 10 

array([11,  7, 11, 12, 10, 13,  5, 12,  9, 12])

In [98]:
np.random.randint(4,15,10)

array([10,  4,  6,  9,  8,  9,  7, 11,  9, 10])

In [99]:
np.random.randint(4,15,(4,3)) ## generate random integer values between 4 and 15 of shape 4 and 3

array([[10, 12, 14],
       [14,  4,  7],
       [10, 14,  4],
       [11,  7,  4]])

In [100]:
num_2 = np.random.randint(4,15,10)

In [101]:
## Slicing and Indexing in Numpy

In [102]:
## Indexing is same as that in Python

In [103]:
num_2

array([ 9,  6, 11,  7,  7, 14, 10, 11, 12, 10])

In [104]:
num_2[4] ## accessing elements using indexing

7

In [105]:
num_2[-3]

11

In [106]:
num_2[2:6] ## slicing in Python

array([11,  7,  7, 14])

In [107]:
num_2[3:]

array([ 7,  7, 14, 10, 11, 12, 10])

In [ ]:
## Indexing and slicing in Multi-Dimensional Arrays

In [108]:
nm = np.random.randint(10, 100 , 20)

In [109]:
np

<module 'numpy' from 'C:\\Users\\SK\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [110]:
nm

array([11, 75, 32, 48, 39, 54, 26, 98, 96, 39, 75, 34, 27, 21, 42, 99, 75,
       25, 11, 24])

In [111]:
nm.resize(5,4)

In [114]:
nm

array([[11, 75, 32, 48],
       [39, 54, 26, 98],
       [96, 39, 75, 34],
       [27, 21, 42, 99],
       [75, 25, 11, 24]])

In [115]:
nm[2,3]

34

In [116]:
nm[1,2]

26

In [117]:
nm[4,2]

11

In [118]:
nm[1,1:] 

array([54, 26, 98])

In [120]:
nm[1:,1]

array([54, 39, 21, 25])

In [119]:
nm[1:,1:]  ## slice the numpy-array

array([[54, 26, 98],
       [39, 75, 34],
       [21, 42, 99],
       [25, 11, 24]])

In [ ]:
## Numpy Braodcsting - never modifies the original numpy array

In [122]:
nm

array([[11, 75, 32, 48],
       [39, 54, 26, 98],
       [96, 39, 75, 34],
       [27, 21, 42, 99],
       [75, 25, 11, 24]])

In [123]:
nm[nm>60]

array([75, 98, 96, 75, 99, 75])

In [124]:
nm[nm>20]

array([75, 32, 48, 39, 54, 26, 98, 96, 39, 75, 34, 27, 21, 42, 99, 75, 25,
       24])

In [125]:
len(nm[nm>20])

18

In [126]:
len(nm[nm>50])

7

In [129]:
nm1 = nm[nm>50]

In [130]:
nm1

array([75, 54, 98, 96, 75, 99, 75])

In [131]:
len(nm1)

7

In [127]:
nm[nm>20].reshape(9,2)

array([[75, 32],
       [48, 39],
       [54, 26],
       [98, 96],
       [39, 75],
       [34, 27],
       [21, 42],
       [99, 75],
       [25, 24]])

In [128]:
nm

array([[11, 75, 32, 48],
       [39, 54, 26, 98],
       [96, 39, 75, 34],
       [27, 21, 42, 99],
       [75, 25, 11, 24]])

In [132]:
list_in_python = [10, 20.0 , "Sachin Shelke" , 5+4j]

In [135]:
type(list_in_python)

list

In [136]:
numpy_arrayy = np.array(list_in_python)

In [137]:
numpy_arrayy

array(['10', '20.0', 'Sachin Shelke', '(5+4j)'], dtype='<U64')

In [138]:
type(numpy_arrayy)

numpy.ndarray

In [141]:
numpy_arrayy1 = np.array(1)

In [140]:
type([1, "Sachin Shelke" , 10.5])

list

In [146]:
numpy_arrayy1 = np.array(1)

In [143]:
numpy_arrayy1

array(1)

In [144]:
type(1)

int

In [147]:
from array import *

In [ ]:
Syntax:
    
arrayName = array(typecode, [initializers])



In [148]:
import array as ar

In [149]:
arr_name = ar.array("i" , [10,20 ,30 ,40 ,50])

In [150]:
arr_name

array('i', [10, 20, 30, 40, 50])

In [151]:
type(arr_name)

array.array

In [152]:
arr_name[0]

10

In [153]:
arr_name[3]

40

In [154]:
array('i', [10, "Sachin Shelke", 30, 40.0, 1+5j])

TypeError: an integer is required (got type str)

That's why we call Array as Homogenous

In [ ]:
Pandas - On Sunday